### ISSUE TITLE
kakboard inserts unneeded newlines on Wayland

### ISSUE THREAD

**Issue by 90-008** [lePerdu/kakboard#10]
Using GNOME on Fedora 32. Every time I do a copy from Firefox, and paste it into kakoune, kakboard inserts unneeded newlines. Here is a picture showing this:
![Ekran Görüntüsü - 2020-05-08 03-02-59](https://user-images.githubusercontent.com/19897088/81355914-895b0200-90d8-11ea-82a9-82877ffd4a38.png)

Seems to only occur when copying from Wayland applications, text copied from Xwayland applications don't behave this way.

**Comment by lePerdu** [comment]
Looks like Firefox running in Wayland copies newlines "Windows style" as CRLF (`\r\n`) rather than just LF (`\n`) (you can see this by copying something and then running `wl-paste -n | hexdump -C`). Other Wayland-native applications, as well as Firefox running under Xwayland, don't do this, so I'm guessing this is a bug in Firefox.

I guess kakboard can just replace the line ending. Kakoune seems to not actually store the CRLF in its buffers, even if `eolformat` is `crlf`, so that makes things pretty easy. I'll work on it later tonight.

**Comment by lePerdu** [comment]
Turns out this is a bit more difficult to do in a cross-platform way. I pushed up a fix using `dos2unix` to the [dos2unix](/lePerdu/kakboard/tree/dos2unix) branch, but it's not a default-installed utility, so I'd rather not force that dependency, especially for a problem that shouldn't exist in the first place. `sed` can't be used because of #2. `tr` may have the same problem as `sed` and also isn't quite "correct" (it removes all `\r`, not just when followed by `\n`).

Another workaround (on your end) would be to create a wrapper script for `wl-paste` that does the substitution and use it for `kakboard_paste_cmd`. E.g.
```
#!/bin/sh
wl-paste -n | dos2unix
# wl-paste -n | tr -d '\r'
# wl-paste -n | sed -e 's/\r\n/\n/'
```

EDIT:
With current master, that above can be done instead by using one of the pipelines as `kakboard_paste_cmd`.

**Comment by 90-008** [comment]
Ah I see. I will just use `dos2unix` for the time being. Should this issue be reported to Firefox?

**Comment by lePerdu** [comment]
There was one submitted a year ago: https://bugzilla.mozilla.org/show_bug.cgi?id=1547595

Last response was 3 months ago saying exactly what I said to do, so it's doesn't look like it's high priority.

**Comment by greenfork** [comment]
I have also stumbled upon this issue and currently it works great, thanks!

**Comment by lePerdu** [comment]
That bug report on Firefox is resolved now. Looks like it will be part of Firefox 81.
